import { AddressType } from '@buildeross/types'
import { type Transaction } from '@buildeross/types'
import { encodeFunctionData } from 'viem'

import { governorAbi } from '../abis'

export interface SetUpdatablePeriodParams {
  governorAddress: AddressType
  proposalUpdatablePeriod?: number // Optional, defaults to 1 day (86400 seconds)
}

/**
 * Creates a transaction to set the Governor's proposal updatable period
 *
 * This should be appended to the upgrade transaction generated by useAvailableUpgrade.
 * The useAvailableUpgrade hook already handles the Governor.upgradeTo() call automatically
 * by detecting the version mismatch and using Manager.governorImpl().
 *
 * @param params.governorAddress - The address of the Governor proxy
 * @param params.proposalUpdatablePeriod - The updatable period in seconds (default: 86400 = 1 day)
 * @returns Transaction to append to the upgrade transaction bundle
 *
 * @example
 * ```ts
 * const { transaction: upgradeTransaction } = useAvailableUpgrade({ chainId, addresses })
 * const setUpdatePeriodTx = createSetUpdatablePeriodTransaction({ governorAddress })
 *
 * // Combine transactions
 * const fullUpgrade = {
 *   ...upgradeTransaction,
 *   transactions: [...upgradeTransaction.transactions, setUpdatePeriodTx]
 * }
 * ```
 */
export function createSetUpdatablePeriodTransaction(
  params: SetUpdatablePeriodParams
): Transaction {
  const {
    governorAddress,
    proposalUpdatablePeriod = 86400, // 1 day default
  } = params

  // Encode the Governor.updateProposalUpdatablePeriod() call
  const calldata = encodeFunctionData({
    abi: governorAbi,
    functionName: 'updateProposalUpdatablePeriod',
    args: [BigInt(proposalUpdatablePeriod)],
  })

  return {
    target: governorAddress,
    functionSignature: 'updateProposalUpdatablePeriod(uint256)',
    calldata,
    value: '',
  }
}
